@Api_HostAddress = http://localhost:5251

GET {{Api_HostAddress}}/after/test-entity
Accept: application/json

###

DELETE {{Api_HostAddress}}/after/test-entity

###

POST {{Api_HostAddress}}/after/test-entity
Content-Type: application/json

{
  "number": 1,
  "amount": 12.34,
  "description": "Test_desc"
}